package tech.williamist.shadowartifacts.items.urkolowsjournal;

public enum EmblemType {

    FRIGHT_EMBLEM,
    TORTURE_EMBLEM,
    BETRAYAL_EMBLEM,
    DOMINANCE_EMBLEM,
    REBIRTH_EMBLEM,
    SCREAMS_EMBLEM,
    SACRIFICE_EMBLEM,
    CRUELTY_EMBLEM,
    SHADOWS_EMBLEM,
    RAGING_EMBLEM,
    COLLAPSE_EMBLEM,
    VIABILITY_EMBLEM,
    FLAMES_EMBLEM,
    PERIL_EMBLEM,
    ANXIETY_EMBLEM,
    LOOMING_FATE_EMBLEM,
    OMNIPRESENCE_EMBLEM,
    SWARMS_EMBLEM,
    NIGHTMARES_EMBLEM,
    OBSERVANCE_EMBLEM,
    WANDERING_EMBLEM,
    DESPISE_EMBLEM,
    BLOODLUST_EMBLEM,
    DESTRUCTION_EMBLEM,
    COWERING_EMBLEM,
    ABSORPTION_EMBLEM,
    SUMMONING_EMBLEM,
    ISOLATION_EMBLEM,
    CURSES_EMBLEM,
    DEATH_EMBLEM,
    CHAOS_EMBLEM

}
